'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { BadgeDollarSign, Save, Search } from 'lucide-react';
import { adminPricingApi } from '@/lib/endpoints';
import { Account, ApiErrorShape, EffectiveEntitlements, PricingMode, PricingPlan } from '@/lib/types';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Alert } from '@/components/ui/Alert';
import { Input, Select, Textarea } from '@/components/ui/Input';
import { Badge } from '@/components/ui/Badge';

interface Overview { pricing_mode: PricingMode; plans: PricingPlan[]; subscription_counts: Record<string, number>; revenue_minor: number; }
interface Override { pricing_enabled: boolean | null; pricing_exempt: boolean; plan_override: string | null; complimentary: boolean; expires_at: string | null; reason: string | null; }
interface UserRow { user: Account; entitlements: EffectiveEntitlements; override: Override | null; }
interface Records { subscriptions: Array<{ id: number; user_id: number; status: string; plan: PricingPlan }>; payments: Array<{ id: number; user_id: number; status: string; amount_minor: number; currency: string }>; audit_log: Array<{ id: number; action: string; target_user_id?: number; created_at: string; reason?: string }>; }

export default function AdminPricingPage() {
  const [overview, setOverview] = useState<Overview | null>(null); const [users, setUsers] = useState<UserRow[]>([]);
  const [records, setRecords] = useState<Records | null>(null); const [search, setSearch] = useState(''); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { const [o, u, r] = await Promise.all([adminPricingApi.overview(), adminPricingApi.users({ search }), adminPricingApi.records()]); setOverview(o.data); setUsers(u.data.users); setRecords(r.data); } catch (e) { setError((e as ApiErrorShape).message); } }, [search]);
  useEffect(() => { void load(); }, [load]);
  async function mode(value: PricingMode) { if (!window.confirm('Change pricing mode? Existing Stripe subscriptions will not be modified.')) return; await adminPricingApi.setMode(value, 'Changed from pricing administration'); await load(); }
  return <div><PageHeader eyebrow="Admin workspace" title="Pricing & subscriptions" icon={BadgeDollarSign} description="Control pricing mode, plans, limits, user access, subscriptions, payments, Stripe references, and audit history." />
    {error && <div className="mt-5"><Alert>{error}</Alert></div>}
    {overview && <><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Pricing mode" value={overview.pricing_mode.replace('PRICING_', '')} /><Stat label="Active" value={overview.subscription_counts.ACTIVE || 0} /><Stat label="Failed" value={overview.subscription_counts.PAYMENT_FAILED || 0} /><Stat label="Cancelled" value={overview.subscription_counts.CANCELLED || 0} /><Stat label="Confirmed revenue" value={`LKR ${(overview.revenue_minor / 100).toLocaleString()}`} /></div>
      <Card className="mt-6"><h2 className="text-lg font-bold text-brand-900">Pricing system</h2><p className="mt-1 text-sm text-muted">Disabling access controls never cancels or deletes Stripe subscriptions.</p><div className="mt-4 max-w-md"><Select label="Mode" value={overview.pricing_mode} onChange={(e) => void mode(e.target.value as PricingMode)}><option value="PRICING_DISABLED">Disabled</option><option value="PRICING_GLOBAL">Enabled for everyone</option><option value="PRICING_SELECTIVE">Selected users only</option></Select></div></Card>
      <section className="mt-6"><h2 className="text-xl font-black text-brand-900">Plans & feature matrix</h2><div className="mt-4 grid gap-5 xl:grid-cols-3">{overview.plans.map((plan) => <PlanEditor key={plan.id} plan={plan} onSaved={load} />)}</div></section></>}
    <section className="mt-8"><h2 className="text-xl font-black text-brand-900">User access overrides</h2><form className="mt-3 flex gap-2" onSubmit={(e) => { e.preventDefault(); void load(); }}><Input aria-label="Search users" placeholder="Name or email" value={search} onChange={(e) => setSearch(e.target.value)} /><Button type="submit"><Search className="h-4 w-4" />Search</Button></form><div className="mt-4 grid gap-4">{users.map((row) => <UserOverride key={row.user.id} row={row} onSaved={load} />)}</div></section>
    {records && <section className="mt-8 grid gap-6 lg:grid-cols-2"><Card><h2 className="text-lg font-bold text-brand-900">Subscriptions & payments</h2><div className="mt-4 space-y-2">{records.subscriptions.slice(0, 20).map((item) => <div key={item.id} className="flex justify-between rounded-xl bg-bg p-3 text-sm"><span>User #{item.user_id} · {item.plan.name}</span><Badge>{item.status}</Badge></div>)}{records.subscriptions.length === 0 && <p className="text-sm text-muted">No subscriptions.</p>}</div></Card><Card><h2 className="text-lg font-bold text-brand-900">Audit log</h2><div className="mt-4 space-y-2">{records.audit_log.slice(0, 20).map((item) => <div key={item.id} className="rounded-xl bg-bg p-3 text-sm"><p className="font-bold">{item.action}</p><p className="text-xs text-muted">{new Date(item.created_at).toLocaleString()} {item.target_user_id ? `· User #${item.target_user_id}` : ''}</p></div>)}{records.audit_log.length === 0 && <p className="text-sm text-muted">No pricing changes yet.</p>}</div></Card></section>}
  </div>;
}

function Stat({ label, value }: { label: string; value: string | number }) { return <Card><p className="text-xs font-bold uppercase text-muted">{label}</p><p className="mt-2 text-xl font-black text-brand-900">{value}</p></Card>; }

function PlanEditor({ plan, onSaved }: { plan: PricingPlan; onSaved: () => Promise<void> }) {
  const [draft, setDraft] = useState(plan); const [saving, setSaving] = useState(false);
  async function save(e: FormEvent) { e.preventDefault(); setSaving(true); try { await adminPricingApi.updatePlan(plan.id, draft); await onSaved(); } finally { setSaving(false); } }
  return <Card><form onSubmit={save} className="space-y-3"><Input label="Plan name" value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /><Input label="Price (minor units)" type="number" min={0} value={draft.price_minor} onChange={(e) => setDraft({ ...draft, price_minor: Number(e.target.value) })} /><Input label="Stripe Product ID" value={draft.stripe_product_id || ''} onChange={(e) => setDraft({ ...draft, stripe_product_id: e.target.value })} /><Input label="Stripe Price ID" value={draft.stripe_price_id || ''} onChange={(e) => setDraft({ ...draft, stripe_price_id: e.target.value })} /><Textarea label="Description" value={draft.description || ''} onChange={(e) => setDraft({ ...draft, description: e.target.value })} />
    <div className="space-y-2 border-t border-border pt-3">{Object.entries(draft.features).map(([key, value]) => <div key={key} className="grid grid-cols-[1fr_auto] items-center gap-2 rounded-xl bg-bg p-2 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={value.enabled} onChange={(e) => setDraft({ ...draft, features: { ...draft.features, [key]: { ...value, enabled: e.target.checked } } })} />{key.replaceAll('_', ' ')}</label>{value.value_type !== 'BOOLEAN' && <span className="flex items-center gap-2"><input className="input w-20" type="number" min={0} disabled={value.unlimited} value={value.limit ?? ''} onChange={(e) => setDraft({ ...draft, features: { ...draft.features, [key]: { ...value, limit: Number(e.target.value) } } })} /><label><input type="checkbox" checked={value.unlimited} onChange={(e) => setDraft({ ...draft, features: { ...draft.features, [key]: { ...value, unlimited: e.target.checked, limit: e.target.checked ? null : value.limit } } })} /> ∞</label></span>}</div>)}</div><Button type="submit" loading={saving}><Save className="h-4 w-4" />Save plan</Button></form></Card>;
}

function UserOverride({ row, onSaved }: { row: UserRow; onSaved: () => Promise<void> }) {
  const [plan, setPlan] = useState(row.override?.plan_override || ''); const [exempt, setExempt] = useState(row.override?.pricing_exempt || false); const [enabled, setEnabled] = useState(row.override?.pricing_enabled ?? false); const [expiry, setExpiry] = useState(row.override?.expires_at?.slice(0, 10) || ''); const [reason, setReason] = useState(row.override?.reason || '');
  const [featureOverrides, setFeatureOverrides] = useState<Record<string, { enabled: boolean; limit: number | null; unlimited: boolean } | null>>({});
  async function save() { await adminPricingApi.updateOverride(row.user.id, { pricing_enabled: enabled, pricing_exempt: exempt, plan: plan || null, complimentary: !!plan, expires_at: expiry ? `${expiry}T23:59:59Z` : null, reason, feature_overrides: featureOverrides }); await onSaved(); }
  return <Card><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold text-brand-900">{row.user.name}</h3><p className="text-sm text-muted">{row.user.email} · Billing {row.entitlements.billing_plan || 'none'} · Effective <strong className="capitalize">{row.entitlements.effective_plan}</strong></p></div><Badge>{row.entitlements.source}</Badge></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} />Pricing enabled</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={exempt} onChange={(e) => setExempt(e.target.checked)} />Exempt</label><Select aria-label="Complimentary plan" value={plan} onChange={(e) => setPlan(e.target.value)}><option value="">No plan override</option><option value="free">Free</option><option value="plus">Complimentary Plus</option><option value="pro">Complimentary Pro</option></Select><Input aria-label="Expiry" type="date" value={expiry} onChange={(e) => setExpiry(e.target.value)} /><Input aria-label="Internal reason" placeholder="Internal reason" value={reason} onChange={(e) => setReason(e.target.value)} /></div>
    <details className="mt-4 rounded-xl border border-border p-3"><summary className="cursor-pointer text-sm font-bold text-brand-700">Effective permissions & individual overrides</summary><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(row.entitlements.features).map(([key, value]) => { const override = featureOverrides[key]; return <div key={key} className="rounded-xl bg-bg p-2 text-xs"><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={override != null} onChange={(e) => setFeatureOverrides({ ...featureOverrides, [key]: e.target.checked ? { enabled: value.enabled, limit: value.limit, unlimited: value.unlimited } : null })} />Override {key.replaceAll('_', ' ')}</label><div className="mt-2 flex items-center gap-2"><label><input type="checkbox" disabled={!override} checked={override?.enabled ?? value.enabled} onChange={(e) => override && setFeatureOverrides({ ...featureOverrides, [key]: { ...override, enabled: e.target.checked } })} /> Enabled</label>{value.value_type !== 'BOOLEAN' && <><input className="input w-20" type="number" min={0} disabled={!override || override.unlimited} value={(override?.limit ?? value.limit) ?? ''} onChange={(e) => override && setFeatureOverrides({ ...featureOverrides, [key]: { ...override, limit: Number(e.target.value) } })} /><label><input type="checkbox" disabled={!override} checked={override?.unlimited ?? value.unlimited} onChange={(e) => override && setFeatureOverrides({ ...featureOverrides, [key]: { ...override, unlimited: e.target.checked, limit: e.target.checked ? null : override.limit } })} /> Unlimited</label></>}</div></div>; })}</div></details>
    <div className="mt-3 flex gap-2"><Button onClick={() => void save()}>Save override</Button><Button variant="ghost" onClick={async () => { await adminPricingApi.updateOverride(row.user.id, { reset: true, reason: 'Reset to subscription/default' }); await onSaved(); }}>Reset</Button></div></Card>;
}
